defmodule AshIntro.Repo.Migrations.CreateEventTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:events, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :event_date, :utc_datetime, null: false
      add :event_location, :text
      add :event_page_id, :uuid, null: false
    end

    create table(:event_pages, primary_key: false) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:events) do
      modify :event_page_id,
             references(:event_pages,
               column: :id,
               name: "events_event_page_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    create index(:events, [:event_page_id])

    alter table(:event_pages) do
      add :crawl_state, :text, default: "ready"
      add :name, :text, null: false
      add :url, :text, null: false
    end
  end

  def down do
    alter table(:event_pages) do
      remove :url
      remove :name
      remove :crawl_state
    end

    drop_if_exists index(:events, [:event_page_id])

    drop constraint(:events, "events_event_page_id_fkey")

    alter table(:events) do
      modify :event_page_id, :uuid
    end

    drop table(:event_pages)

    drop table(:events)
  end
end
